apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-clinic-tekton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinic
  template:
    metadata:
      labels:
        app: clinic
    spec:
      containers:
      - name: pet-clinic
        image: gangadhariy/tekton:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-loadbalancer-service
spec:
  selector:
    app: onlinebookstore
  ports:
    - protocol: TCP
      port: 8080  
      targetPort: 8080  
      nodePort: 32000   
  type: NodePort
