apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinebookstore-tekton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onlinebookstore
  template:
    metadata:
      labels:
        app: onlinebookstore
    spec:
      containers:
      - name: onlinebookstore
        image: rony399/openshift-devops:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-loadbalancer-service
spec:
  selector:
    app: onlinebookstore
  ports:
    - protocol: TCP
      port: 8080  
      targetPort: 8080  
      nodePort: 32000   
  type: NodePort
